### ISSUE TITLE
恭喜大神回归 & 交流一下

### ISSUE THREAD

**Issue by winwnx** [Ronein/HP-ZHAN-66-Pro-14-G3-OC-EFI#1]
没其他方式联系大神，只好通过issue来恭喜大神回归了。
PS：
我用了你最新的OC0.7.6_BigSur_11.6_v1.5，发现比上一版本小好多了，很棒啊。

我的机型是i5版本的，我自己扩展了内存，只用了一根32G的，系统是安装在一个ssd硬盘上的。

开机使用都很正常，但系统的睡眠一直是有问题，偶尔可以，但大多数时候不行。不知道是什么原因。我尝试了很多办法，在bios中的设置等。网上说的 HibernationFixup扩展，我看到你的efi中也已经包括了。我试过不勾选这个扩展，对系统也没啥影响，睡眠的问题现象也是一样的。

我的问题现象是这样的，合盖后，电源灯还是亮的（从缝隙中可以看到），大约要过20 - 30秒，开始快闪（如果可以正常睡眠，应该是慢闪）然后电源指示灯（在dc插口旁边）开始橙色快闪，大约3-5秒后，变成白色，此时电源风扇高速转一秒（声音很大的那种），然后系统看上去就关机了。此时再按电源键，是无法开机的（如果是接电源时合盖，是可以开机的），需要长按电源键15秒以上，才能再次开机。有时还会在屏幕上显示一个电池标识，看上去象是电池电量基本耗尽的标识。

你看看能给些思路或建议吗？感激不尽。

**Comment by mao-design** [comment]
我也遇到了这个问题了，最后把nvram中的boot-args引导项里的igfxfw=2删除即可解决无法睡眠的问题😊

**Comment by v125534514** [comment]
>
1. 我一开始也有你这个休眠问题，后面是HibernationFixup kext+ EC ACPI 才修复的，按理说我的EFI文件里面已经涵盖，你还出现这个问题也超出我的范围了。
2. 至于说合盖开盖无湖面，按电源键无反应，这个也是因为休眠问题，因为这个时候系统没有正确获取你已经想要退出休眠状态，也没正确识别你按电源键的意图。。 长按电源键其实就是强制断电关机了；

**Comment by v125534514** [comment]
> 

加入igfxfw=2 这个选项是因为，我经常会外接显示器做扩展，这个选项我记得作用是强制所有HDMI接口在线，我这边不启用这个选项的话，外接显示器的话，是没有反应的（虽然打开了，在外接显示器的时候，基本都需要拔插2次才可以正常显示）

**Comment by v125534514** [comment]
@winwnx 并非大佬，大家多沟通交流。。现在最大的毛病就是声卡，不插耳麦的时候，麦克风无法正常工作。 接了耳麦之后，就能正常

**Comment by mao-design** [comment]
> > 
> 
> 加入igfxfw=2 这个选项是因为，我经常会外接显示器做扩展，这个选项我记得作用是强制所有HDMI接口在线，我这边不启用这个选项的话，外接显示器的话，是没有反应的（虽然打开了，在外接显示器的时候，基本都需要拔插2次才可以正常显示）

我使用HDMI之后主机的屏幕就黑屏了，但HDMI屏幕可以显示，然后我在HDMI屏幕上点击睡眠，等屏幕黑屏之后在迅速移动鼠标这样，电脑的主屏幕就显示正常了HDMI也正常了，

**Comment by mao-design** [comment]
> >
> 1. 我一开始也有你这个休眠问题，后面是HibernationFixup kext+ EC ACPI 才修复的，按理说我的EFI文件里面已经涵盖，你还出现这个问题也超出我的范围了。
> 2. 至于说合盖开盖无湖面，按电源键无反应，这个也是因为休眠问题，因为这个时候系统没有正确获取你已经想要退出休眠状态，也没正确识别你按电源键的意图。。 长按电源键其实就是强制断电关机了；

有可能是电脑配置有点不同，我的是i5的版本，所以可能对我的不起作用，也不知道是不是这个问题😂

**Comment by mao-design** [comment]
> > > 
> > 
> > 加入igfxfw=2 这个选项是因为，我经常会外接显示器做扩展，这个选项我记得作用是强制所有HDMI接口在线，我这边不启用这个选项的话，外接显示器的话，是没有反应的（虽然打开了，在外接显示器的时候，基本都需要拔插2次才可以正常显示）
> 
> 我使用HDMI之后主机的屏幕就黑屏了，但HDMI屏幕可以显示，然后我在HDMI屏幕上点击睡眠，等屏幕黑屏之后在迅速移动鼠标这样，电脑的主屏幕就显示正常了HDMI也正常了，

我把igfxfw=2这个删掉的，在这里也非常感谢🙏大佬的efi，自己搞太难了😭

**Comment by mao-design** [comment]
> @winwnx 并非大佬，大家多沟通交流。。现在最大的毛病就是声卡，不插耳麦的时候，麦克风无法正常工作。 接了耳麦之后，就能正常

哦，对了，还有就是大佬，你那个efi里面那个禁用独显的dsdt好像有点问题，刚开机的时候一切正常，但是睡眠之后在唤醒，这耗电量就不正常了

**Comment by mao-design** [comment]
> > @winwnx 并非大佬，大家多沟通交流。。现在最大的毛病就是声卡，不插耳麦的时候，麦克风无法正常工作。 接了耳麦之后，就能正常
> 
> 哦，对了，还有就是大佬，你那个efi里面那个禁用独显的dsdt好像有点问题，刚开机的时候一切正常，但是睡眠之后在唤醒，这耗电量就不正常了

然后我用SSDT-NDGP_OFF.aml这个dsdt补丁，以上的问题就没有出现了

**Comment by mao-design** [comment]
> > > @winwnx 并非大佬，大家多沟通交流。。现在最大的毛病就是声卡，不插耳麦的时候，麦克风无法正常工作。 接了耳麦之后，就能正常
> > 
> > 哦，对了，还有就是大佬，你那个efi里面那个禁用独显的dsdt好像有点问题，刚开机的时候一切正常，但是睡眠之后在唤醒，这耗电量就不正常了
> 
> 然后我用SSDT-NDGP_OFF.aml这个dsdt补丁，以上的问题就没有出现了

然后原来禁用独显的那个补丁就没有用了

**Comment by mao-design** [comment]
> > > 
> > 
> > 加入igfxfw=2 这个选项是因为，我经常会外接显示器做扩展，这个选项我记得作用是强制所有HDMI接口在线，我这边不启用这个选项的话，外接显示器的话，是没有反应的（虽然打开了，在外接显示器的时候，基本都需要拔插2次才可以正常显示）
> 
> 我使用HDMI之后主机的屏幕就黑屏了，但HDMI屏幕可以显示，然后我在HDMI屏幕上点击睡眠，等屏幕黑屏之后在迅速移动鼠标这样，电脑的主屏幕就显示正常了HDMI也正常了，

之后，重新拔了在重接HDMI就没有黑屏的情况了😂

**Comment by mao-design** [comment]
> >
> 1. 我一开始也有你这个休眠问题，后面是HibernationFixup kext+ EC ACPI 才修复的，按理说我的EFI文件里面已经涵盖，你还出现这个问题也超出我的范围了。
> 2. 至于说合盖开盖无湖面，按电源键无反应，这个也是因为休眠问题，因为这个时候系统没有正确获取你已经想要退出休眠状态，也没正确识别你按电源键的意图。。 长按电源键其实就是强制断电关机了；

这是我目前遇到的情况，还有就是最新版的oc0.7.7触控板无法驱动，使用itlwmx.kext这个驱动会导致无法开机，然后我把oc换成oc0.7.5就正常了😂，这是我目前遇到的情况以及解决方法，希望对你有所帮助

**Comment by v125534514** [comment]
> > @winwnx之后不是大佬大家多交流。。最大的毛病就是，不插耳麦的时候，现在不能正常麦工作了。
> 
> 还有大佬，你但是那个里面禁止独显的dsd似乎有点问题，刚开机的时候，一切都刚刚正常启动了

额~我是在BIOS上直接关闭了独显，所以这里这个限制独显的作用其实相当于没有的。

**Comment by v125534514** [comment]
> 



> > > 
> > 
> > 
> > 
> > 1. 我一开始也有你这个休眠问题，后面是HibernationFixup kext+ EC ACPI的，理说我的EFI文件里面才修复，你也出现这个问题超出我的范围了。
> > 2. 说合盖开盖湖无所发光面，按电源键无反应，这也是因为休眠问题，因为这个时候系统没有获取你想要休眠的状态，也没有正确识别你电源键设备的发光面。电源键其实就是那个了；
> 
> 这是我目前的情况，还有就是最新版 oc0.7.7.7 的然后遇到板子无法驱动，使用 itmx.ext 驱动会导致无法启动，我把 oc0.7.5 换成正常了😂，这是我目前遇到的情况以及解决方法，希望对你有所帮助

我昨天刚新上传了0.7.8 版本的，可以替换下~~0.7.7 版本是因为vooops2 的kext有问题，有时开机识别不到导致的，0.7.8 没这个问题

**Comment by v125534514** [comment]
> > > > 
> > > 
> > > 
> > > 加入igfxfw2这个选项是因为，虽然我会经常外接显示器执行扩展，这个选项我记得作用是强制所有接口在线，我没有启用这个选项，外接显示器，是反应的（打开了，在外接显示器的时候，基本都需要拔插2次才可以正常显示）
> > 
> > 
> > 我使用HDMI之后的主机就黑屏了，但是HDMI屏幕可以显示，然后我在HDMI屏幕上点击屏幕，等黑屏在移动鼠标之后，电脑的主屏幕就正常显示了HDMI了，
> 
> 之后，重新拔插了在重接HDMI就没有黑屏的情况了😂

我的电脑在第一次新接的外显时，会出现你说的情况，外显正常显示，內显黑屏，这个时候我的操作是，盖上盖子，再重新打开就两个显示器正常

**Comment by v125534514** [comment]
> itlwmx.kext这个驱动会导致无



> 这是我目前遇到的情况，还有就是最新版的oc0.7.7触控板无法驱动，使用itlwmx.kext这个驱动会导致无法开机，然后我把oc换成oc0.7.5就正常了😂，这是我目前遇到的情况以及解决方法，希望对你有所帮助

itlwmx.kext 是要配合heliport 这个软件才能正常使用的；所以我都是直接用Airportitlwn.kext ，贪图方便

**Comment by mao-design** [comment]
> > 
> 
> 
> 
> > > > 
> > > 
> > > 
> > > 
> > > 1. 我一开始也有你这个休眠问题，后面是HibernationFixup kext+ EC ACPI的，理说我的EFI文件里面才修复，你也出现这个问题超出我的范围了。
> > > 2. 说合盖开盖湖无所发光面，按电源键无反应，这也是因为休眠问题，因为这个时候系统没有获取你想要休眠的状态，也没有正确识别你电源键设备的发光面。电源键其实就是那个了；
> > 
> > 这是我目前的情况，还有就是最新版 oc0.7.7.7 的然后遇到板子无法驱动，使用 itmx.ext 驱动会导致无法启动，我把 oc0.7.5 换成正常了😂，这是我目前遇到的情况以及解决方法，希望对你有所帮助
> 
> 我昨天刚新上传了0.7.8 版本的，可以替换下~~0.7.7 版本是因为vooops2 的kext有问题，有时开机识别不到导致的，0.7.8 没这个问题

好的👌

**Comment by mao-design** [comment]
> > > 
> > 
> > 
> > 
> > > > > 
> > > > 
> > > > 
> > > > 
> > > > 1. 我一开始也有你这个休眠问题，后面是HibernationFixup kext+ EC ACPI的，理说我的EFI文件里面才修复，你也出现这个问题超出我的范围了。
> > > > 2. 说合盖开盖湖无所发光面，按电源键无反应，这也是因为休眠问题，因为这个时候系统没有获取你想要休眠的状态，也没有正确识别你电源键设备的发光面。电源键其实就是那个了；
> > > 
> > > 这是我目前的情况，还有就是最新版 oc0.7.7.7 的然后遇到板子无法驱动，使用 itmx.ext 驱动会导致无法启动，我把 oc0.7.5 换成正常了😂，这是我目前遇到的情况以及解决方法，希望对你有所帮助
> > 
> > 我昨天刚新上传了0.7.8 版本的，可以替换下~~0.7.7 版本是因为vooops2 的kext有问题，有时开机识别不到导致的，0.7.8 没这个问题
> 
> 好的👌

但我觉得现在的efi和系统已经稳定了，所以不想折腾了😂

**Comment by winwnx** [comment]
> 我也遇到了这个问题了，最后把nvram中的boot-args引导项里的igfxfw=2删除即可解决无法睡眠的问题😊

今天试了一下，果然可以解决睡眠问题。感谢感谢。
